---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: go-store
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/go

---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: stack
spec:
  id: io.buildpacks.stacks.bionic
  buildImage:
    image: paketobuildpacks/build:base-cnb
  runImage:
    image: paketobuildpacks/run:base-cnb

---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: go-builder
spec:
  serviceAccountRef:
    name: cartographer-example-registry-creds-sa
    namespace: default
  tag: 10.161.116.240:5000/example-gitwriter-sc-go-builder
  stack:
    name: stack
    kind: ClusterStack
  store:
    name: go-store
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/go

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"10.161.116.240:5000":{"password":"a-very-hard-to-guess-password","username":"a-username-of-mine"}}}'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartographer-example-registry-creds-sa
secrets:
  - name: registry-credentials
imagePullSecrets:
  - name: registry-credentials